fix: Move global variables to correct location before function declarations
Fixed undeclared variable errors by moving global variable declarations
to the top of main.c, after includes but before all function definitions.

ERROR:
  main.c:99: error: 'thermal_ctx' undeclared
  main.c:105: error: 'temp_frame_buffer' undeclared

Root cause:
- print_statistics() function (line 60) uses thermal_ctx and temp_frame_buffer
- But variables were declared later (line 122-127) after function definitions
- C requires variables to be declared before use

Solution:
- Moved global variable declarations to top of file (after includes)
- Removed duplicate declarations from later in the file

Changes:
- src/main.c:
  - Lines 22-27: Added global variable declarations
    - static thermal_frame_t frame_buffer;
    - static temperature_frame_t temp_frame_buffer;
    - static Thermal_SIMD_Context_t thermal_ctx;
  - Lines 122-127: Removed duplicate variable declarations

Build should now succeed - this was the last compilation error!